name: PHPUnit

on: push
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  larastan:
    name: Test application
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
#    services:
#      postgres:
#        image: postgres:10.8
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: test
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: "Create" file for credentials
        run: cp tests/FacebookTestCredentials.php.dist tests/FacebookTestCredentials.php
      - name: Start tests
        env:
          FACEBOOK_APP_ID: test
          FACEBOOK_APP_SECRET: test
        run: ./vendor/bin/phpunit
